DATA SEGMENT PARA 'DATA'
    A DW 0000h
    B DW 7777h
DATA ENDS
STAC SEGMENT PARA STACK 'STAC'
    STA1 DW 100 DUP(?)
STAC ENDS
CODE SEGMENT PARA 'CODE'
    ASSUME CS:CODE,DS:DATA
    ASSUME SS:STAC,ES:DATA
    
    STAR PROC FAR
    PUSH DS
    XOR AX,AX
    PUSH AX
    MOV AX,DATA
    MOV DS,AX
    MOV ES,AX
    CALL TT
    OK:MOV AX,4C00H
    INT 21H
    STAR ENDP

    TT PROC
    LEA DX,A
    MOV AH,9
    INT 21H
    RET
    TT ENDP
CODE ENDS
    END STAR
