DATA SEGMENT PARA 'DATA'
    STRING DB 'asdFsaFgSSazX', '$'
    COUNT_STRING EQU $-STRING
    DEST DB COUNT_STRING DUP(?)
DATA ENDS
STAC SEGMENT PARA STACK 'STAC'
    STA1 DW 100 DUP(?)
STAC ENDS
CODE SEGMENT PARA 'CODE'
    ASSUME CS:CODE,DS:DATA,SS:STAC,ES:DATA

    MAIN PROC FAR
    MOV AX,DATA
    MOV DS,AX
    MOV ES,AX
    MOV AX,STAC
    MOV SS,AX
    LEA SI,STRING
    LEA DI,DEST
    MOV CX,COUNT_STRING
REPEAT:
    MOV AL,[SI]
    AND AL,0DFH
    INC SI
    STOSB
    LOOP REPEAT
    MOV AH,4CH
    INT 21h
    MAIN ENDP

    PRINT_STRING PROC FAR
    PUSH 
    POP AX
    LEA [SP+4],AX
    PRINT_STRING ENDP
CODE ENDS
    END MAIN

