function(AssureNotInSourceBuilds)
    get_filename_component(srcDir "${CMAKE_SOURCE_DIR}" REALPATH)
    get_filename_component(binDir "${CMAKE_BINARY_DIR}" REALPATH)

    if("${srcDir}" STREQUAL "${binDir}")
        message("########################################")
        message("# The build file should not be place in the same place as the source code.")
        message("# Instead you should run cmake in a seperate build directory")
        message("# For exmaple, assuming that you are in the root directory.")
        message("# Run command >mkdir build | cd build | cmake ..")
        message("# Or >cd .. | mkdir build | cd build | cmake ../<project_folder>")
        message(FATAL_ERROR "Quitting configration")
    endif()
endfunction()